//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Netfilmes.Repository;

//namespace Netfilmes.Migrations
//{
//    [DbContext(typeof(ApplicationContext))]
//    [Migration("20200821050505_Netfilmes")]
//    partial class Netfilmes
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "3.1.7")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("Netfilmes.Business.Entidades.Filme", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<bool>("Ativo")
//                        .HasColumnType("bit");

//                    b.Property<DateTime>("DataDeCriacao")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime2")
//                        .HasDefaultValueSql("CONVERT(DATE, GETDATE())");

//                    b.Property<int?>("GeneroId")
//                        .HasColumnType("int");

//                    b.Property<int?>("LocacaoId")
//                        .HasColumnType("int");

//                    b.Property<string>("Nome")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("GeneroId");

//                    b.HasIndex("LocacaoId");

//                    b.ToTable("Filme");
//                });

//            modelBuilder.Entity("Netfilmes.Business.Entidades.Genero", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<bool>("Ativo")
//                        .HasColumnType("bit");

//                    b.Property<DateTime>("DataDeCriacao")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime2")
//                        .HasDefaultValueSql("CONVERT(DATE, GETDATE())");

//                    b.Property<string>("Nome")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Genero");
//                });

//            modelBuilder.Entity("Netfilmes.Business.Entidades.Locacao", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Cpf")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("DataDaLocacao")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime2")
//                        .HasDefaultValueSql("CONVERT(DATE, GETDATE())");

//                    b.HasKey("Id");

//                    b.ToTable("Locacao");
//                });

//            modelBuilder.Entity("Netfilmes.Business.Entidades.Usuario", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<DateTime>("DataDeCriacao")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime2")
//                        .HasDefaultValueSql("CONVERT(DATE, GETDATE())");

//                    b.Property<string>("Nome")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Senha")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Usuario");
//                });

//            modelBuilder.Entity("Netfilmes.Business.Entidades.Filme", b =>
//                {
//                    b.HasOne("Netfilmes.Business.Entidades.Genero", "Genero")
//                        .WithMany("Filmes")
//                        .HasForeignKey("GeneroId")
//                        .OnDelete(DeleteBehavior.SetNull);

//                    b.HasOne("Netfilmes.Business.Entidades.Locacao", "Locacao")
//                        .WithMany("Filmes")
//                        .HasForeignKey("LocacaoId");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
